# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP-address')),
                ('name', models.CharField(max_length=20, verbose_name='\u0418\u043c\u044f \u043a\u0430\u043c\u0435\u0440\u044b')),
                ('user', models.CharField(default='root', editable=False, max_length=4)),
                ('password', models.CharField(default='.2476p', editable=False, max_length=6)),
            ],
            options={
                'verbose_name': '\u043a\u0430\u043c\u0435\u0440\u0430',
                'verbose_name_plural': '\u043a\u0430\u043c\u0435\u0440\u044b',
            },
        ),
    ]
