# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_reboot', '0002_cameras_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameras',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cameras',
            name='user',
        ),
    ]
