# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_reboot', '0003_auto_20170602_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='password',
            field=models.CharField(default='password', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='cameras',
            name='user',
            field=models.CharField(default='empty', editable=False, max_length=5),
        ),
    ]
