# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_mac', models.CharField(max_length=10)),
                ('mac_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='number.Number')),
            ],
            options={
                'db_table': 'mac',
            },
        ),
    ]
