# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logpass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_num', models.CharField(max_length=10)),
                ('tel_pass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Logpass',
            },
        ),
        migrations.AlterField(
            model_name='mac',
            name='mac_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='number.Logpass'),
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
