# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_auto_20161127_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mac',
            old_name='mac_mac',
            new_name='mac_adr',
        ),
    ]
