# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters_data', models.IntegerField(verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u0441\u043e \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430')),
                ('month', models.DateField(verbose_name='\u041c\u0435\u0441\u044f\u0446')),
            ],
            options={
                'verbose_name': '\u043f\u043e\u043a\u0430\u0437\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u0423\u0441\u043b\u0443\u0433\u0430')),
                ('price_below_100', models.IntegerField(verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0434\u043e 100')),
                ('price_up_100', models.IntegerField(verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u043f\u043e\u0441\u043b\u0435 100')),
            ],
            options={
                'verbose_name': '\u0443\u0441\u043b\u0443\u0433\u0430',
                'verbose_name_plural': '\u0443\u0441\u043b\u0443\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Services', verbose_name='\u0423\u0441\u043b\u0443\u0433\u0430'),
        ),
    ]
