# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170710_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '\u043a \u043e\u043f\u043b\u0430\u0442\u0435', 'verbose_name_plural': '\u043a \u043e\u043f\u043b\u0430\u0442\u0435'},
        ),
        migrations.AddField(
            model_name='services',
            name='id_name',
            field=models.CharField(default=datetime.datetime(2017, 7, 11, 7, 13, 24, 468943, tzinfo=utc), max_length=20, unique=True, verbose_name='\u0418\u043c\u044f \u0434\u043b\u044f \u0441\u0441\u044b\u043b\u043a\u0438(\u0442\u0440\u0430\u043d\u0441\u043b\u0438\u0442)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='meters_data',
            field=models.IntegerField(verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u0441\u043e \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430'),
        ),
    ]
