# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170711_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='id_name',
            field=models.CharField(max_length=20, verbose_name='\u0418\u043c\u044f \u0434\u043b\u044f \u0441\u0441\u044b\u043b\u043a\u0438(\u0442\u0440\u0430\u043d\u0441\u043b\u0438\u0442)'),
        ),
    ]
