# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170711_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delay',
            field=models.IntegerField(default=1, verbose_name='\u041d\u0430\u043a\u0440\u0443\u0447\u0435\u043d\u043e'),
            preserve_default=False,
        ),
    ]
